[project]
name = "tfm-master-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sap-rpt-oss",
    "pandas",
    "numpy",
    "scikit-learn",
    "sentence-transformers",
    "tabpfn",
    "ipykernel",
    "python-dotenv",
    "pyod",
    "mlflow",
    "tabpfn-extensions",
    "peft",
    "accelerate",
    "shap",
    "datasets",
    "safetensors",
]

[tool.uv.sources]
sap-rpt-oss = { git = "https://github.com/SAP-samples/sap-rpt-1-oss.git" }
